### ISSUE TITLE
graphicx package

### ISSUE THREAD

**Issue by rolfn** [csachs/luaimageembed#2]
I suggest to change 
```
\RequirePackage{luacode}
```
to 
```
\RequirePackage{luacode,graphicx}
```
because `graphicx` is necessary in all cases.

...Rolf

**Comment by csachs** [comment]
I had submitted the package earlier today to CTAN, so I guess that might be a thing for v0.2 then.

I had not added this, since I did not want to couple it to either graphicx or pgf tightly.
But since it is a LaTeX package, and the [pgfmanual](http://mirrors.ctan.org/graphics/pgf/base/doc/pgfmanual.pdf) (page 1146) states "For all other backends, PGF currently maps its commands back to the graphicx package.", you're right and it could be changed as suggested.
